apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app4-fw2
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/gautamo/app4
          env:
            - name: TARGET
              value: "Python Sample v1"
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
