apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app3-fw1
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/metric: "rps"
    spec:
      containers:
      - env:
        - name: TARGET
          value: Python Sample v1
        image: docker.io/gautamo/app3
