apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app3-fw1
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/gautamo/app3
          env:
            - name: TARGET
              value: "Python Sample v1"
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
