apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app2
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/gautamo/app2
          env:
            - name: TARGET
              value: "Python Sample v1"
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "4"
        autoscaling.knative.dev/target: "2"
