apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app2-fw2
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/metric: "rps"
    spec:
      containers:
      - image: docker.io/gautamo/app2
