apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: autoscale-go-fw1
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/target: '10'
    spec:
      containers:
      - image: gcr.io/knative-samples/autoscale-go:0.1
