apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app5-fw2
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
      - env:
        - name: TARGET
          value: Python Sample v1
        image: docker.io/gautamo/app5
